# Generated by Django 3.2.25 on 2026-01-06 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20260102_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='slug',
        ),
    ]
