# Generated by Django 6.0.3 on 2026-03-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='image_url',
        ),
        migrations.AddField(
            model_name='productimages',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
