# Generated by Django 5.1.3 on 2026-04-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='allow_backorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='track_inventory',
            field=models.BooleanField(default=True),
        ),
    ]
