# Generated by Django 6.0.3 on 2026-03-09 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productimages_image_url_productimages_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='option1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants_option1', to='products.productoptionvalue'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='option2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants_option2', to='products.productoptionvalue'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='option3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants_option3', to='products.productoptionvalue'),
        ),
    ]
