# Generated by Django 5.1.3 on 2026-04-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productvariant_allow_backorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='track_inventory',
            field=models.BooleanField(default=False),
        ),
    ]
