# Generated by Django 5.1.3 on 2026-04-10 10:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productvariant_track_inventory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='cnic_back',
            field=models.ImageField(blank=True, null=True, upload_to='shop/cnic/back/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='cnic_front',
            field=models.ImageField(blank=True, null=True, upload_to='shop/cnic/front/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='cnic_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='CNIC number must be exactly 13 digits.', regex='^\\d{13}$')]),
        ),
        migrations.AddField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='shop',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='shop/banners/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shop/logos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shop',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['status'], name='products_sh_status_123b10_idx'),
        ),
    ]
