# Generated by Django 5.1.3 on 2026-05-05 06:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_shop_cnic_back_shop_cnic_front_shop_cnic_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['position', 'name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='productoption',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productoptionvalue',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productreviewimage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={},
        ),
        migrations.AlterModelOptions(
            name='variantimage',
            options={'ordering': ['position']},
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='products_pr_product_cee51f_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='products_pr_sku_dcab68_idx',
        ),
        migrations.RemoveIndex(
            model_name='shop',
            name='products_sh_handle_71e334_idx',
        ),
        migrations.RemoveIndex(
            model_name='shop',
            name='products_sh_owner_i_373ebe_idx',
        ),
        migrations.RemoveIndex(
            model_name='shop',
            name='products_sh_status_123b10_idx',
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='variantimage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='shop',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productreviewimage',
            name='variant_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.variantimage'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='cnic_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{13}$')]),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['slug'], name='products_sh_slug_95cb2c_idx'),
        ),
    ]
