# Generated by Django 5.1.3 on 2026-05-05 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='status',
            new_name='product_status',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='status',
            new_name='shop_status',
        ),
    ]
