# Generated by Django 5.1.3 on 2026-03-31 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0002_productimage_productreview_productreviewimage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='province',
        ),
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.RenameIndex(
            model_name='cart',
            new_name='cart_user_status_idx',
            old_name='cart_cart_user_id_2c8a21_idx',
        ),
        migrations.RenameIndex(
            model_name='cart',
            new_name='cart_session_status_idx',
            old_name='cart_cart_session_81d746_idx',
        ),
        migrations.RenameIndex(
            model_name='cartitem',
            new_name='cartitem_cart_product_idx',
            old_name='cart_cartit_cart_id_4bd8c3_idx',
        ),
        migrations.RenameIndex(
            model_name='cartitem',
            new_name='cartitem_cart_variant_idx',
            old_name='cart_cartit_cart_id_8609d3_idx',
        ),
        migrations.RenameIndex(
            model_name='shippingaddress',
            new_name='address_user_default_idx',
            old_name='cart_shippi_user_id_927ba9_idx',
        ),
        migrations.RenameIndex(
            model_name='shippingaddress',
            new_name='address_user_type_idx',
            old_name='cart_shippi_user_id_17bd04_idx',
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon_code',
            field=models.CharField(blank=True, help_text='Applied coupon code', max_length=50, verbose_name='Coupon Code'),
        ),
        migrations.AddField(
            model_name='cart',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Discount Amount'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='sku',
            field=models.CharField(blank=True, help_text='Product SKU at add time', max_length=100, verbose_name='SKU'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant_name',
            field=models.CharField(blank=True, help_text='Snapshot of variant name at add time', max_length=255, verbose_name='Variant Name'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='alternate_phone',
            field=models.CharField(blank=True, help_text='Optional alternate contact number', max_length=20, verbose_name='Alternate Phone'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, help_text='Django session key for guest users', max_length=40, null=True, verbose_name='Session Key'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('abandoned', 'Abandoned'), ('converted', 'Converted to Order')], default='active', help_text='Active = current cart, Converted = ordered, Abandoned = not completed', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Authenticated user (null for guest users)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Product variant (if product has variants)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='products.productvariant', verbose_name='Variant'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='full_name',
            field=models.CharField(help_text='Recipient full name', max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Set as default shipping address', verbose_name='Default Address'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone_number',
            field=models.CharField(help_text='Recipient contact number', max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='street_address',
            field=models.TextField(help_text='House/Flat number, Street, Area', verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['-created_at'], name='cart_created_at_idx'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
