# Generated by Django 5.1.3 on 2026-03-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_fulfillment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='billingdetail',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='billingdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
    ]
