""" ============================================================
    Django settings for core project.
    Author: Muhammad Noman
    Generated by 'django-admin startproject' using Django 5.2.7.
    Documentation:
        https://docs.djangoproject.com/en/5.2/topics/settings/
=============================================================== """

from pathlib import Path
import os


""" =============== BASE & SECURITY CONFIGURATION =============== """

BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p=3-93xin6_y494m)=*xg!ros5qoq8*8(c3^h2==!82*l97z0i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


""" =============== APPLICATION DEFINITION =============== """

INSTALLED_APPS = [
    "jazzmin",
    # Default Django Apps
    'django.contrib.admin', 
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-Party Apps
    'rest_framework',
    'crispy_forms',
    'tailwind',
    'drf_yasg',


    # Custom Apps
    'apps.admin_panel',
    'apps.inventory_tracking',
    'apps.main',
    'apps.order_fulfillment',
    'apps.products',
    'apps.shipment_monitoring',
    'apps.supplier_monitoring',
    'apps.supplychain',
    'apps.users',
    'apps.utilities',
]


""" =============== DJANGO REST FRAMEWORK CONFIG =============== """

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

""" Custom User Mode """

AUTH_USER_MODEL = 'users.User'


""" =============== MIDDLEWARE CONFIGURATION =============== """

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


""" =============== URL & TEMPLATE SETTINGS =============== """

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # custom templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


""" =============== DATABASE CONFIGURATION =============== """

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


""" =============== PASSWORD VALIDATION =============== """

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


""" =============== INTERNATIONALIZATION =============== """

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


""" =============== STATIC & MEDIA FILES =============== """

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

# Media files (for uploaded images like profile pictures)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


""" =============== DEFAULT AUTO FIELD =============== """

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ================= Jazmin Admin Configuration =================

JAZMIN_SETTINGS = {
    "site_title": "Footwear Admin",
    "site_header": "Footwear Dashboard",
    "welcome_sign": "Welcome to Footwear Management System",
    "site_brand": "Footwear",
    "copyright": "© 2025 Muhammad Noman",
    "site_logo": None,  # you can add 'images/logo.png' if available
    "login_logo": None,
    "login_logo_dark": None,
    "site_icon": None,

    # ================= Top Menu =================
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"app": "users"},
        {"app": "products"},
        {"app": "orders"},
    ],

    # ================= Sidebar =================
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_models": [],
    "order_with_respect_to": ["users", "products", "orders"],

    # ================= Icons =================
    "icons": {
        "auth": "fas fa-users-cog",
        "users.User": "fas fa-user",
        "users.Profile": "fas fa-id-card",
        "users.Address": "fas fa-map-marker-alt",
        "users.ContactDetail": "fas fa-phone",
        "products": "fas fa-boxes",
        "orders": "fas fa-shopping-cart",
    },

    # ================= UI Customization =================
    "custom_css": None,
    "custom_js": None,
    "related_modal_active": True,
}

# ================= Jazmin UI Theme =================
JAZMIN_UI_TWEAKS = {
    "theme": "flatly",  # flatly / darkly / cyborg / literal etc.
    "dark_mode_theme": "darkly",
    "navbar": "navbar-dark bg-dark",
    "sidebar": "sidebar-dark-primary",
    "brand_colour": "navbar-dark",
    "accent": "accent-info",
    "navbar_fixed": True,
    "sidebar_fixed": True,
    "footer_fixed": False,
    "body_small_text": True,
    "sidebar_collapse": False,
    "actions_sticky_top": True,
}
