# Generated by Django 5.1.3 on 2026-04-08 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order_fulfillment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('shipment_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('courier_company', models.CharField(choices=[('leopards', 'Leopards Courier'), ('tcs', 'TCS'), ('dhl', 'DHL'), ('pakistan_post', 'Pakistan Post'), ('call_courier', 'Call Courier'), ('other', 'Other')], max_length=20)),
                ('tracking_number', models.CharField(max_length=100)),
                ('tracking_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Dispatch'), ('picked', 'Picked Up by Courier'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed', 'Delivery Failed'), ('returned', 'Returned to Sender')], db_index=True, default='pending', max_length=20)),
                ('estimated_delivery_date', models.DateField(blank=True, null=True)),
                ('shipped_date', models.DateTimeField(blank=True, null=True)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('customer_notified', models.BooleanField(default=False)),
                ('delivery_attempts', models.PositiveSmallIntegerField(default=0)),
                ('failure_reason', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='order_fulfillment.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentTrackingLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('status', models.CharField(help_text="e.g., 'Picked Up', 'In Transit', 'Out for Delivery'", max_length=50, verbose_name='Status')),
                ('location', models.CharField(blank=True, help_text='City or facility name', max_length=255, verbose_name='Location')),
                ('description', models.TextField(blank=True, help_text='Detailed status description for customer', verbose_name='Description')),
                ('api_response', models.JSONField(blank=True, help_text='Raw response from courier API', null=True, verbose_name='API Response')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_logs', to='shipment_monitoring.shipment', verbose_name='Shipment')),
            ],
            options={
                'verbose_name': 'Shipment Tracking Log',
                'verbose_name_plural': 'Shipment Tracking Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['shipment_number'], name='shipment_mo_shipmen_ed1c37_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tracking_number'], name='shipment_mo_trackin_fa58c5_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status'], name='shipment_mo_status_cc748b_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['order'], name='shipment_mo_order_i_363692_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmenttrackinglog',
            index=models.Index(fields=['shipment', '-created_at'], name='tracking_shipment_idx'),
        ),
    ]
