# Generated by Django 5.1.3 on 2026-04-20 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otp_alter_user_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
