# Generated by Django 6.0.3 on 2026-03-27 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete flag', verbose_name='Is Active')),
                ('payment_method', models.CharField(choices=[('card', 'Credit/Debit Card'), ('paypal', 'PayPal'), ('bank', 'Bank Transfer'), ('cod', 'Cash on Delivery')], default='cod', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_details', to='cart.cart')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_details', to='cart.shippingaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billing Detail (Deprecated)',
                'verbose_name_plural': 'Billing Details (Deprecated)',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete flag', verbose_name='Is Active')),
                ('order_number', models.CharField(editable=False, help_text='Unique order reference number', max_length=20, unique=True, verbose_name='Order Number')),
                ('order_status', models.CharField(choices=[('pending', 'Pending Payment'), ('processing', 'Processing'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Order Status')),
                ('payment_method', models.CharField(choices=[('card', 'Credit/Debit Card'), ('paypal', 'PayPal'), ('bank', 'Bank Transfer'), ('cod', 'Cash on Delivery'), ('stripe', 'Stripe'), ('razorpay', 'Razorpay')], default='cod', max_length=20, verbose_name='Payment Method')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', max_length=20, verbose_name='Payment Status')),
                ('transaction_id', models.CharField(blank=True, help_text='Payment gateway transaction ID', max_length=100, null=True, verbose_name='Transaction ID')),
                ('payment_gateway_response', models.JSONField(blank=True, help_text='Raw response from payment gateway', null=True, verbose_name='Payment Gateway Response')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tax')),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Shipping Fee')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Discount')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Amount')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Shipped At')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered At')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelled At')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Tracking Number')),
                ('courier_company', models.CharField(blank=True, max_length=100, verbose_name='Courier Company')),
                ('tracking_url', models.URLField(blank=True, verbose_name='Tracking URL')),
                ('customer_notes', models.TextField(blank=True, help_text='Special instructions from customer', verbose_name='Customer Notes')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for staff', verbose_name='Admin Notes')),
                ('coupon_code', models.CharField(blank=True, max_length=50, verbose_name='Coupon Code')),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_orders', to='cart.shippingaddress', verbose_name='Billing Address')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cart.cart', verbose_name='Original Cart')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='cart.shippingaddress', verbose_name='Shipping Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete flag', verbose_name='Is Active')),
                ('status_from', models.CharField(blank=True, max_length=20, verbose_name='Status From')),
                ('status_to', models.CharField(max_length=20, verbose_name='Status To')),
                ('action', models.CharField(help_text='What action was performed', max_length=100, verbose_name='Action')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='order_fulfillment.order', verbose_name='Order')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_actions', to=settings.AUTH_USER_MODEL, verbose_name='Performed By')),
            ],
            options={
                'verbose_name': 'Order History',
                'verbose_name_plural': 'Order Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete flag', verbose_name='Is Active')),
                ('product_name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('variant_name', models.CharField(blank=True, max_length=255, verbose_name='Variant Name')),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='SKU')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit Price')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Price')),
                ('returned_quantity', models.PositiveIntegerField(default=0, verbose_name='Returned Quantity')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Refund Amount')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order_fulfillment.order', verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product', verbose_name='Product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.productvariant', verbose_name='Variant')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='order_fulfi_order_n_0cc00e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'order_status'], name='order_fulfi_user_id_547d00_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_status', 'created_at'], name='order_fulfi_order_s_6e49d6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='order_fulfi_payment_20a151_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shipping_address'], name='order_fulfi_shippin_dc22cb_idx'),
        ),
        migrations.AddIndex(
            model_name='orderhistory',
            index=models.Index(fields=['order'], name='order_fulfi_order_i_362e24_idx'),
        ),
        migrations.AddIndex(
            model_name='orderhistory',
            index=models.Index(fields=['status_to', 'created_at'], name='order_fulfi_status__35c08c_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='order_fulfi_order_i_484755_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='order_fulfi_product_ccad33_idx'),
        ),
    ]
