# Generated by Django 3.2.25 on 2025-12-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Original price', max_digits=10)),
                ('discount_percentage', models.PositiveSmallIntegerField(default=0, help_text='0 - 100')),
                ('button_text', models.CharField(default='Shop Collection', max_length=100)),
                ('button_link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='banners/%Y/%m/%d')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
