# Generated by Django 5.1.3 on 2026-04-08 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banners',
        ),
    ]
