# Generated by Django 3.2.25 on 2025-12-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banners',
            name='button_link',
        ),
        migrations.AddField(
            model_name='banners',
            name='category',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women')], default='men', max_length=100),
        ),
    ]
