# Generated by Django 5.1.3 on 2026-04-08 08:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('name', models.CharField(max_length=255, verbose_name='Warehouse Name')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Warehouse Code')),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('is_main', models.BooleanField(default=False)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='products.shop')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLevel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('available_quantity', models.PositiveIntegerField(default=0, verbose_name='Available Quantity')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, verbose_name='Reserved Quantity')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_levels', to='products.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory_tracking.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('movement_type', models.CharField(choices=[('sale', 'Sale'), ('return', 'Customer Return'), ('adjustment', 'Manual Adjustment')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory_tracking.inventorylevel')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='positive_stock_movement')],
            },
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['shop'], name='inventory_t_shop_id_88ce5f_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['is_main'], name='inventory_t_is_main_f65ab2_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylevel',
            index=models.Index(fields=['variant'], name='inventory_t_variant_d5c34d_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylevel',
            index=models.Index(fields=['warehouse'], name='inventory_t_warehou_d59723_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorylevel',
            constraint=models.UniqueConstraint(fields=('variant', 'warehouse'), name='unique_variant_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='inventorylevel',
            constraint=models.CheckConstraint(condition=models.Q(('available_quantity__gte', 0)), name='available_qty_positive'),
        ),
    ]
